export default {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    SET_RECORDS: "SET_RECORDS",
    SET_SELECTED_RECORD_LOADING: 'SET_SELECTED_RECORD_LOADING',
    SET_SELECTED_RECORD: "SET_SELECTED_RECORD",
    SET_ROLES: "SET_ROLES",
};
